name: ztg
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  provider: ^6.0.5
  flutter_local_notifications: ^18.0.1
  hive: ^2.2.3
  timer_builder: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.8.0

dev_dependencies:
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Electric
      fonts:
        - asset: assets/fonts/Electric.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter:
      assets:
        enabled: true
      fonts:
        enabled: true
